"""Helpers for extracting and cleaning downloaded books into chapter-only text."""

from __future__ import annotations

import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory

from pypdf import PdfReader


BOOK_FILE_SUFFIXES = frozenset({".pdf", ".epub", ".mobi", ".azw3"})
_MAX_TITLE_WORDS = 14
_OCR_SPACED_HEADING_RE = re.compile(r"^(?:[A-Za-z]\s+){3,}[A-Za-z]$")
_CHAPTER_WORD_RE = re.compile(
    r"^(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|"
    r"fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|twenty[- ]one|"
    r"twenty[- ]two|twenty[- ]three|twenty[- ]four|twenty[- ]five|twenty[- ]six|"
    r"twenty[- ]seven|twenty[- ]eight|twenty[- ]nine|thirty)\.?\b",
    re.IGNORECASE,
)
_EXPLICIT_CHAPTER_RE = re.compile(
    r"^chapter\s+(?:\d+|[ivxlcdm]+|one|two|three|four|five|six|seven|eight|nine|ten|"
    r"eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|"
    r"twenty[- ]one|twenty[- ]two|twenty[- ]three|twenty[- ]four|twenty[- ]five|"
    r"twenty[- ]six|twenty[- ]seven|twenty[- ]eight|twenty[- ]nine|thirty)\b",
    re.IGNORECASE,
)
_INLINE_NUMBERED_HEADING_RE = re.compile(
    r"^(?:chapter\s+)?(?:\d+|[ivxlcdm]+|one|two|three|four|five|six|seven|eight|nine|ten|"
    r"eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|"
    r"twenty[- ]one|twenty[- ]two|twenty[- ]three|twenty[- ]four|twenty[- ]five|"
    r"twenty[- ]six|twenty[- ]seven|twenty[- ]eight|twenty[- ]nine|thirty)"
    r"(?:\s*[-.:)]\s*|\s+)[A-Za-z\"'“‘].+$",
    re.IGNORECASE,
)
_INTRO_HEADING_RE = re.compile(r"^(introduction|prologue|preface)$", re.IGNORECASE)
_BACK_MATTER_RE = re.compile(
    r"^(notes|source notes|references|bibliography|glossary|index|acknowledg(?:e)?ments|"
    r"about the author|about the book|image credits|photo credits|illustration credits|"
    r"permissions|appendix(?:\b| [a-z0-9]+)|afterword|endnotes|epilogue|conclusions?|"
    r"postscript)\b",
    re.IGNORECASE,
)
_TOC_MARKER_RE = re.compile(r"^(contents|table of contents)\b", re.IGNORECASE)
_FRONT_MATTER_RE = re.compile(
    r"^(title page|cover|dedication|copyright|also by\b|cast of characters|"
    r"list of illustrations|illustrations|maps|list of maps|about the author|"
    r"other books by this author|epigraph|acknowledg(?:e)?ments|"
    r"praise for\b|acclaim for\b|advance praise\b)",
    re.IGNORECASE,
)
_FRONT_MATTER_BLOCK_RE = re.compile(
    r"^(cast of characters|list of illustrations|illustrations|maps|list of maps)\b",
    re.IGNORECASE,
)
_STRUCTURAL_WRAPPER_RE = re.compile(
    r"^part\s+(?:\d+|[ivxlcdm]+|one|two|three|four|five|six|seven|eight|nine|ten)\b",
    re.IGNORECASE,
)
_NOISE_RE = re.compile(
    r"(oceanofpdf|dokumen\.pub|vdoc\.pub|https?://|www\.|@|all rights reserved|"
    r"converted by calibre|calibre\b|ebook-convert|generated by unregistered calibre)",
    re.IGNORECASE,
)
_PAGE_NUMBER_RE = re.compile(r"^(?:page\s+)?[\[\(]?\s*\d{1,4}\s*[\]\)]?$", re.IGNORECASE)
_PAGE_SEPARATOR_RE = re.compile(r"^(?:[-_=~*#•·\s]{3,}|[0-9\s\-]{5,})$")
_IMAGE_CAPTION_RE = re.compile(
    r"^(figure|fig\.|map|photo|plate|illustration|table)\s+[a-z0-9][a-z0-9.\-: ]*$",
    re.IGNORECASE,
)
_TOC_ENTRY_RE = re.compile(r"^.{1,120}\.{2,}\s*\d{1,4}$")
_ISBN_LINE_RE = re.compile(r"^(?:isbn(?:-1[03])?:?\s*)?[0-9xX\- ]{10,}$")
_NOTE_NUMBER_RE = re.compile(r"^\d{1,4}[.)]$")
_BOOK_PREFIX_RE = re.compile(r"^(?:_?oceanofpdf\.com_|dokumen\.pub_|vdoc\.pub_)+", re.IGNORECASE)
_ISBN_FILENAME_RE = re.compile(r"(?:[-_ ]?97[89][0-9xX\-]{8,})+")


@dataclass(frozen=True)
class CleanBookResult:
    source_path: Path
    output_path: Path
    chapter_count: int
    word_count: int


def list_recent_book_files(downloads_dir: Path, limit: int = 13) -> list[Path]:
    """Return the newest supported book-like files in descending modified order."""

    candidates = [
        path
        for path in downloads_dir.iterdir()
        if path.is_file() and path.suffix.lower() in BOOK_FILE_SUFFIXES
    ]
    return sorted(candidates, key=lambda path: path.stat().st_mtime, reverse=True)[:limit]


def derive_output_filename(path: Path) -> str:
    """Build a stable cleaned output file name from a source file name."""

    stem = _BOOK_PREFIX_RE.sub("", path.stem)
    stem = _ISBN_FILENAME_RE.sub("", stem)
    stem = re.sub(r"\([^)]*\)", "", stem)
    stem = stem.replace("&", " and ")
    stem = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").lower()
    if not stem:
        stem = "book"
    return f"{stem}.cleaned.txt"


def extract_book_text(path: Path) -> str:
    """Extract text using the best available tool for the file type."""

    suffix = path.suffix.lower()
    with TemporaryDirectory(prefix="book-clean-") as tmp_dir_name:
        tmp_dir = Path(tmp_dir_name)
        if suffix == ".pdf":
            return _extract_pdf_text(path, tmp_dir)
        if suffix in {".epub", ".mobi", ".azw3"}:
            return _extract_ebook_text(path, tmp_dir)
    raise ValueError(f"Unsupported source format: {path}")


def clean_book_text(raw_text: str) -> str:
    """Reduce extracted text to chapter-only narrative content."""

    normalized_lines = _normalize_lines(raw_text)
    filtered_lines = _drop_noise_lines(normalized_lines)
    filtered_lines = _drop_preface_toc_blocks(filtered_lines)
    content_lines = _trim_to_content_window(filtered_lines)
    sections = _extract_sections(content_lines)
    if not sections:
        raise ValueError("No chapter-like sections found in extracted text.")

    rendered_sections: list[str] = []
    for chapter_number, body in enumerate(sections, start=1):
        cleaned_body = _collapse_body(body)
        if not cleaned_body:
            continue
        rendered_sections.append(f"Chapter {chapter_number}\n\n{cleaned_body}")
    if not rendered_sections:
        raise ValueError("Chapter extraction produced no usable narrative text.")
    return "\n\n".join(rendered_sections).strip() + "\n"


def clean_book_file(source_path: Path, output_dir: Path) -> CleanBookResult:
    """Extract, clean, and write a single downloaded book."""

    raw_text = extract_book_text(source_path)
    cleaned_text = clean_book_text(raw_text)
    chapter_count = len(re.findall(r"^Chapter \d+$", cleaned_text, flags=re.MULTILINE))
    word_count = len(re.findall(r"\b\w+\b", cleaned_text))
    if word_count < 5000:
        raise ValueError(
            f"Cleaned output is too sparse to trust ({word_count} words extracted after cleanup)."
        )
    output_path = output_dir / derive_output_filename(source_path)
    output_path.write_text(cleaned_text, encoding="utf-8")
    return CleanBookResult(
        source_path=source_path,
        output_path=output_path,
        chapter_count=chapter_count,
        word_count=word_count,
    )


def _extract_pdf_text(path: Path, tmp_dir: Path) -> str:
    txt_path = tmp_dir / f"{path.stem}.txt"
    result = subprocess.run(
        ["pdftotext", "-enc", "UTF-8", "-nopgbrk", str(path), str(txt_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0 and txt_path.exists():
        text = txt_path.read_text(encoding="utf-8", errors="ignore")
        if text.strip():
            return text
    text = _extract_pdf_text_with_mutool(path, tmp_dir)
    if text.strip():
        return text
    return _extract_pdf_text_with_pypdf(path)


def _extract_pdf_text_with_pypdf(path: Path) -> str:
    reader = PdfReader(str(path))
    if reader.is_encrypted:
        raise ValueError(f"Encrypted PDF files are not supported: {path}")
    pages = [(page.extract_text() or "").strip() for page in reader.pages]
    text = "\n\n".join(page for page in pages if page)
    if not text.strip():
        raise ValueError(f"Unable to extract text from PDF: {path}")
    return text


def _extract_ebook_text(path: Path, tmp_dir: Path) -> str:
    txt_path = tmp_dir / f"{path.stem}.txt"
    calibre_config_dir = tmp_dir / "calibre-config"
    calibre_config_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["CALIBRE_CONFIG_DIRECTORY"] = str(calibre_config_dir)
    result = subprocess.run(
        ["ebook-convert", str(path), str(txt_path)],
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"ebook-convert failed for '{path.name}': {(result.stderr or result.stdout).strip()}"
        )
    text = txt_path.read_text(encoding="utf-8", errors="ignore")
    if not text.strip():
        raise ValueError(f"ebook-convert produced no text for: {path}")
    return text


def _extract_pdf_text_with_mutool(path: Path, tmp_dir: Path) -> str:
    txt_path = tmp_dir / f"{path.stem}.mutool.txt"
    result = subprocess.run(
        ["mutool", "convert", "-F", "text", "-o", str(txt_path), str(path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0 or not txt_path.exists():
        return ""
    return txt_path.read_text(encoding="utf-8", errors="ignore")


def _normalize_lines(text: str) -> list[str]:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n").replace("\x0c", "\n")
    normalized = re.sub(r"(?<=\w)-\n(?=\w)", "", normalized)
    lines: list[str] = []
    for line in normalized.split("\n"):
        collapsed = re.sub(r"\s+", " ", line.strip())
        if _OCR_SPACED_HEADING_RE.fullmatch(collapsed):
            collapsed = collapsed.replace(" ", "")
        lines.append(collapsed)
    return lines


def _drop_noise_lines(lines: list[str]) -> list[str]:
    candidate_counts = Counter(
        line
        for line in lines
        if line
        and len(line) <= 80
        and len(line.split()) <= 12
        and not _looks_like_heading(line)
        and not _looks_like_sentence(line)
    )
    repeated_headers = {line for line, count in candidate_counts.items() if count >= 3}

    cleaned: list[str] = []
    previous_blank = False
    for index, line in enumerate(lines):
        if not line:
            if not previous_blank:
                cleaned.append("")
            previous_blank = True
            continue
        if line in repeated_headers:
            continue
        if _looks_like_multiline_numbered_heading(lines, index):
            cleaned.append(line)
            previous_blank = False
            continue
        if _is_noise_line(line):
            continue
        cleaned.append(line)
        previous_blank = False
    while cleaned and not cleaned[0]:
        cleaned.pop(0)
    while cleaned and not cleaned[-1]:
        cleaned.pop()
    return cleaned


def _drop_preface_toc_blocks(lines: list[str]) -> list[str]:
    cleaned: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if _is_toc_marker(line):
            index = _skip_toc_block(lines, index + 1)
            continue
        if _FRONT_MATTER_BLOCK_RE.match(line):
            index = _skip_front_matter_block(lines, index + 1)
            continue
        cleaned.append(line)
        index += 1
    return cleaned


def _trim_to_content_window(lines: list[str]) -> list[str]:
    headings = [index for index in range(len(lines)) if _is_heading_at(lines, index)]
    start_index = _find_content_start_index(lines, headings)
    if start_index is None:
        raise ValueError("Unable to find a starting chapter, introduction, or prologue.")

    end_index = len(lines)
    for index in range(start_index + 1, len(lines)):
        if _BACK_MATTER_RE.match(lines[index] or ""):
            end_index = index
            break
    trimmed = lines[start_index:end_index]
    while trimmed and not trimmed[0]:
        trimmed.pop(0)
    while trimmed and not trimmed[-1]:
        trimmed.pop()
    return trimmed


def _find_content_start_index(lines: list[str], headings: list[int]) -> int | None:
    if not headings:
        return None
    numbered_headings = [index for index in headings if _looks_like_multiline_numbered_heading(lines, index)]
    for heading_index in numbered_headings:
        next_heading_index = _next_heading_index(lines, heading_index + 1)
        if _heading_has_local_body(lines, heading_index, next_heading_index):
            return heading_index
    for position, heading_index in enumerate(headings):
        next_heading_index = headings[position + 1] if position + 1 < len(headings) else len(lines)
        if _heading_has_local_body(lines, heading_index, next_heading_index):
            return heading_index
    return None


def _extract_sections(lines: list[str]) -> list[list[str]]:
    headings = [index for index in range(len(lines)) if _is_heading_at(lines, index)]
    if not headings:
        return []

    sections: list[list[str]] = []
    for position, heading_index in enumerate(headings):
        next_heading_index = headings[position + 1] if position + 1 < len(headings) else len(lines)
        body_start_index = _body_start_index(lines, heading_index, next_heading_index)
        body_lines = lines[body_start_index:next_heading_index]
        if _body_word_count(body_lines) == 0 or not _body_has_prose(body_lines, min_total_words=4):
            continue
        sections.append(body_lines)
    return sections


def _body_start_index(lines: list[str], heading_index: int, next_heading_index: int) -> int:
    body_start_index = _heading_span_end(lines, heading_index, next_heading_index)
    if body_start_index != heading_index + 1:
        return body_start_index
    title_index = _next_nonblank_index(lines, heading_index + 1, next_heading_index)
    if title_index is not None and _looks_like_title_line(lines[title_index]):
        return title_index + 1
    return body_start_index


def _looks_like_multiline_numbered_heading(lines: list[str], index: int) -> bool:
    line = lines[index]
    if not line:
        return False
    if _INTRO_HEADING_RE.match(line):
        return True
    if _looks_like_inline_numbered_heading(line):
        return True
    if _EXPLICIT_CHAPTER_RE.match(line):
        return True
    if not _is_standalone_chapter_token(line):
        return False
    next_index = _next_nonblank_index(lines, index + 1, len(lines))
    if next_index is None:
        return True
    next_line = lines[next_index]
    return _looks_like_title_line(next_line) or _is_prose_like_line(next_line, len(next_line.split()))


def _is_heading_at(lines: list[str], index: int) -> bool:
    line = lines[index]
    if not line:
        return False
    if _looks_like_multiline_numbered_heading(lines, index):
        return True
    return _looks_like_heading(line)


def _heading_span_end(lines: list[str], heading_index: int, next_heading_index: int) -> int:
    line = lines[heading_index]
    if _looks_like_inline_numbered_heading(line):
        return heading_index + 1

    end_index = heading_index + 1
    scan_index = _next_nonblank_index(lines, heading_index + 1, next_heading_index)
    while scan_index is not None:
        scan_line = lines[scan_index]
        if not _looks_like_title_line(scan_line):
            break
        end_index = scan_index + 1
        scan_index = _next_nonblank_index(lines, scan_index + 1, next_heading_index)
    return end_index


def _collapse_body(lines: list[str]) -> str:
    blocks: list[str] = []
    current_lines: list[str] = []
    for line in lines:
        if not line:
            if current_lines:
                block = " ".join(current_lines).strip()
                if block:
                    blocks.append(block)
                current_lines = []
            continue
        if _is_noise_line(line):
            continue
        current_lines.append(line)
    if current_lines:
        block = " ".join(current_lines).strip()
        if block:
            blocks.append(block)
    return "\n\n".join(blocks).strip()


def _looks_like_heading(line: str) -> bool:
    return bool(
        not _STRUCTURAL_WRAPPER_RE.match(line)
        and not _FRONT_MATTER_RE.match(line)
        and (
            _INTRO_HEADING_RE.match(line)
        or _EXPLICIT_CHAPTER_RE.match(line)
        or _looks_like_inline_numbered_heading(line)
        or _is_standalone_chapter_token(line)
        )
    )


def _looks_like_inline_numbered_heading(line: str) -> bool:
    match = _INLINE_NUMBERED_HEADING_RE.match(line)
    if not match:
        return False
    numeric_prefix = re.match(r"^(?:chapter\s+)?(\d+)\b", line, re.IGNORECASE)
    if numeric_prefix and (len(numeric_prefix.group(1)) >= 4 or int(numeric_prefix.group(1)) > 60):
        return False
    prefix_remainder = re.match(
        r"^(?:chapter\s+)?(?:\d+|one|two|three|four|five|six|seven|eight|nine|ten|"
        r"eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|"
        r"twenty|twenty[- ]one|twenty[- ]two|twenty[- ]three|twenty[- ]four|"
        r"twenty[- ]five|twenty[- ]six|twenty[- ]seven|twenty[- ]eight|"
        r"twenty[- ]nine|thirty)(?:\s*[-.:)]\s*|\s+)(.+)$",
        line,
        re.IGNORECASE,
    )
    if prefix_remainder and not _looks_like_heading_phrase(prefix_remainder.group(1)):
        return False
    return len(line.split()) <= 18 and not _looks_like_sentence(line)


def _is_standalone_chapter_token(line: str) -> bool:
    if not line or len(line.split()) > 4:
        return False
    if not _CHAPTER_WORD_RE.match(line):
        return False
    return bool(re.fullmatch(r"[A-Za-z0-9 .-]+", line))


def _looks_like_title_line(line: str) -> bool:
    if not line or _looks_like_heading(line) or _BACK_MATTER_RE.match(line):
        return False
    if _is_noise_line(line):
        return False
    words = line.split()
    if len(words) > _MAX_TITLE_WORDS:
        return False
    if line.endswith((".", "?", "!", ";", ":")):
        return False
    if _looks_like_heading_phrase(line):
        return True
    if _looks_like_sentence(line):
        return False
    return any(character.isalpha() for character in line)


def _looks_like_sentence(line: str) -> bool:
    words = line.split()
    return len(words) >= 8 or line.endswith((".", "?", "!", ";", ":"))


def _is_noise_line(line: str) -> bool:
    if not line:
        return True
    return bool(
        _NOISE_RE.search(line)
        or _FRONT_MATTER_RE.match(line)
        or _STRUCTURAL_WRAPPER_RE.match(line)
        or _PAGE_NUMBER_RE.fullmatch(line)
        or _PAGE_SEPARATOR_RE.fullmatch(line)
        or _IMAGE_CAPTION_RE.match(line)
        or _TOC_ENTRY_RE.fullmatch(line)
        or _ISBN_LINE_RE.fullmatch(line)
    )


def _next_nonblank_index(lines: list[str], start: int, stop: int) -> int | None:
    for index in range(start, stop):
        if lines[index]:
            return index
    return None


def _body_word_count(lines: list[str]) -> int:
    return len(re.findall(r"\b\w+\b", " ".join(line for line in lines if line)))


def _probe_body_lines(lines: list[str], heading_index: int) -> list[str]:
    probe: list[str] = []
    seen_headings = 0
    nonblank_count = 0
    for index in range(heading_index + 1, len(lines)):
        line = lines[index]
        if _looks_like_heading(line):
            seen_headings += 1
            if seen_headings >= 3:
                break
        probe.append(line)
        if line:
            nonblank_count += 1
            if nonblank_count >= 40:
                break
    return probe


def _heading_has_local_body(lines: list[str], heading_index: int, next_heading_index: int) -> bool:
    body_start_index = _body_start_index(lines, heading_index, next_heading_index)
    body_lines = lines[body_start_index:next_heading_index]
    prose_offset = _first_prose_offset(body_lines)
    if prose_offset is None:
        return False
    if _has_leading_navigation_cluster(lines, heading_index) and prose_offset > 4:
        return False
    lead_lines = [line for line in body_lines[:prose_offset] if line]
    if any(_BACK_MATTER_RE.match(line) or _FRONT_MATTER_RE.match(line) for line in lead_lines):
        return False
    return _body_has_prose(body_lines, min_total_words=8)


def _body_has_prose(lines: list[str], min_total_words: int) -> bool:
    prose_like_lines = 0
    total_words = 0
    strong_prose_lines = 0
    for line in lines:
        if not line or _is_noise_line(line):
            continue
        word_count = len(line.split())
        total_words += word_count
        if _is_prose_like_line(line, word_count):
            prose_like_lines += 1
            if line.endswith((".", "!", ";", ":")) and word_count >= min_total_words:
                strong_prose_lines += 1
        if prose_like_lines >= 2:
            return True
    return strong_prose_lines >= 1 and total_words >= min_total_words


def _is_toc_marker(line: str) -> bool:
    return bool(line and _TOC_MARKER_RE.match(line))


def _skip_toc_block(lines: list[str], start: int) -> int:
    index = start
    while index < len(lines):
        line = lines[index]
        if not line or _is_noise_line(line):
            index += 1
            continue
        if _looks_like_heading(line):
            next_heading_index = _next_heading_index(lines, index + 1)
            if _heading_has_local_body(lines, index, next_heading_index):
                return index
        index += 1
    return start


def _skip_front_matter_block(lines: list[str], start: int) -> int:
    index = start
    while index < len(lines):
        line = lines[index]
        if not line or _is_noise_line(line):
            index += 1
            continue
        if _looks_like_heading(line):
            return index
        if _looks_like_sentence(line):
            return index
        index += 1
    return start


def _next_heading_index(lines: list[str], start: int) -> int:
    for index in range(start, len(lines)):
        if _looks_like_heading(lines[index]):
            return index
    return len(lines)


def _is_prose_like_line(line: str, word_count: int) -> bool:
    if line.endswith((".", "!", ";", ":")):
        return word_count >= 4
    if word_count < 6:
        return False
    if "?" in line:
        return word_count >= 10 and not _looks_like_title_line(line)
    return word_count >= 12 and not _looks_like_title_line(line)


def _looks_like_heading_phrase(text: str) -> bool:
    words = re.findall(r"[A-Za-z][A-Za-z'’-]*", text)
    if not words:
        return False
    stopwords = {"a", "an", "and", "as", "at", "by", "for", "from", "in", "of", "on", "or", "the", "to", "with"}
    significant = [word for word in words if word.lower() not in stopwords]
    if not significant:
        return False
    capitalized = sum(1 for word in significant if word[0].isupper())
    return capitalized >= max(1, len(significant) - 1)


def _first_prose_offset(lines: list[str]) -> int | None:
    for offset, line in enumerate(lines):
        if not line or _is_noise_line(line):
            continue
        if _is_prose_like_line(line, len(line.split())):
            return offset
    return None


def _has_leading_navigation_cluster(lines: list[str], heading_index: int) -> bool:
    recent_nonblank: list[str] = []
    for index in range(heading_index - 1, -1, -1):
        line = lines[index]
        if not line:
            continue
        recent_nonblank.append(line)
        if len(recent_nonblank) >= 40:
            break
    short_nonprose = 0
    prose_lines = 0
    for line in recent_nonblank:
        word_count = len(line.split())
        if _is_prose_like_line(line, word_count):
            prose_lines += 1
            continue
        if word_count <= 12 and not _looks_like_sentence(line):
            short_nonprose += 1
    return short_nonprose >= 8 and prose_lines <= 1
