"""Prompt builders for active LLM stages."""

from podcast_agent.prompts.instructions import (
    book_summary_instructions,
    chapter_summary_instructions,
    episode_architecture_instructions,
    episode_planning_instructions,
    episode_writing_no_citations_instructions,
    episode_writing_instructions,
    excerpt_extraction_instructions,
    grounding_validation_instructions,
    narrative_strategy_enrichment_instructions,
    narrative_strategy_skeleton_instructions,
    narrative_state_reconciler_instructions,
    passage_extraction_instructions,
    primitive_function_tagging_instructions,
    primitive_substrate_extraction_instructions,
    repair_instructions,
    scene_discovery_instructions,
    spoken_delivery_instructions,
    style_audit_instructions,
    synthesis_primitives_instructions,
    theme_decomposition_instructions,
)

__all__ = [
    "book_summary_instructions",
    "chapter_summary_instructions",
    "episode_architecture_instructions",
    "episode_planning_instructions",
    "episode_writing_no_citations_instructions",
    "episode_writing_instructions",
    "excerpt_extraction_instructions",
    "grounding_validation_instructions",
    "narrative_strategy_enrichment_instructions",
    "narrative_strategy_skeleton_instructions",
    "narrative_state_reconciler_instructions",
    "passage_extraction_instructions",
    "primitive_function_tagging_instructions",
    "primitive_substrate_extraction_instructions",
    "repair_instructions",
    "scene_discovery_instructions",
    "spoken_delivery_instructions",
    "style_audit_instructions",
    "synthesis_primitives_instructions",
    "theme_decomposition_instructions",
]
