"""Prompt builders for spoken-delivery rewriting."""

from __future__ import annotations


TONE_SUFFIXES = {
    "educational": "Prioritize clarity, continuity, and calm explanatory narration.",
    "educational_suspenseful": (
        "Prioritize clarity first. Add only a light undercurrent of suspense through pacing and transitions, "
        "without becoming theatrical."
    ),
    "documentary_podcast": (
        "Prioritize clarity and factual fidelity. Use documentary-style narration with light scene-setting, "
        "measured momentum, and occasional signposting to guide the listener."
    ),
    "reflective_history": (
        "Prioritize clarity and historical reflection, while remaining concrete and grounded in the source material."
    ),
}


def build_spoken_delivery_instructions(
    *,
    tone_preset: str,
    target_expansion_ratio: float,
    max_expansion_ratio: float,
) -> str:
    """Build the primary spoken-delivery prompt."""

    tone_suffix = TONE_SUFFIXES.get(tone_preset, TONE_SUFFIXES["educational_suspenseful"])
    target_percent = int(round(target_expansion_ratio * 100))
    max_percent = int(round(max_expansion_ratio * 100))
    return (
        "You are a narration rewriter in a podcast production pipeline. Your job is to\n"
        "adapt source text so it sounds natural when read aloud by a single narrator,\n"
        "while preserving the original information almost exactly.\n\n"
        "===============================================================\n"
        " TASK DEFINITION\n"
        "===============================================================\n\n"
        "Convert the CURRENT SEGMENT from written prose into spoken-word narration.\n\n"
        "This is an ADAPTATION for the ear, not a creative rewrite. Think of it as what\n"
        "a skilled audiobook editor does: restructure sentences for clarity when spoken,\n"
        "smooth over constructions that only work on the page, and add just enough\n"
        "connective tissue to keep a listener oriented -- without injecting new substance.\n\n"
        "===============================================================\n"
        " INPUT FORMAT\n"
        "===============================================================\n\n"
        "You will receive three clearly labeled blocks:\n\n"
        "  [PREVIOUS SEGMENT]  -- Read-only. For transition context only.\n"
        "  [CURRENT SEGMENT]   -- Rewrite THIS and only this.\n"
        "  [NEXT SEGMENT]      -- Read-only. For transition context only.\n\n"
        "Adjacent segments may be empty (start/end of episode). Never pull facts from\n"
        "adjacent segments into your output. Never relocate facts out of the current\n"
        "segment. The boundaries are hard walls.\n\n"
        "===============================================================\n"
        " INFORMATION FIDELITY (highest priority)\n"
        "===============================================================\n\n"
        "- Preserve ALL claims, facts, names, numbers, dates, and causal relationships.\n"
        "- Do not add examples, analogies, facts, or interpretations not in the source.\n"
        "- Do not upgrade hedged language (\"may\", \"some researchers believe\") to\n"
        "  definitive statements, or vice versa.\n"
        "- Do not merge or reorder paragraphs. Sentence-level reordering within a\n"
        "  paragraph is allowed only when it improves spoken flow without changing\n"
        "  meaning.\n"
        "- If a passage is highly technical or data-dense, prioritize clarity over\n"
        "  smoothness. It is better to sound slightly stiff than to lose precision.\n\n"
        "===============================================================\n"
        " LENGTH TARGET\n"
        "===============================================================\n\n"
        f"Output word count must fall between {target_percent}% and {max_percent}% of\n"
        "the current segment's word count.\n\n"
        f"If your draft exceeds {max_percent}%, cut connective filler first, then\n"
        "simplify phrasing. Do NOT cut facts to meet the target.\n\n"
        "===============================================================\n"
        " SPOKEN-FORM ADAPTATIONS (required)\n"
        "===============================================================\n\n"
        "Apply these mechanical transformations everywhere they help:\n\n"
        "1. Break any sentence longer than ~35 words into 2-3 shorter sentences.\n"
        "2. Merge back-to-back sentences under ~8 words into a single natural clause.\n"
        "3. Replace page-only constructions:\n"
        "   - Parentheticals -> separate sentence or appositive clause\n"
        "   - Semicolons -> period + short connective (\"And so...\", \"That meant...\")\n"
        "   - Dense noun stacks (>3 modifiers) -> unpack into a relative clause\n"
        "   - \"The former / the latter\" -> repeat the noun\n"
        "   - \"As shown in Figure X\" / \"See table below\" -> drop or replace with\n"
        "     a brief verbal restatement of the data point\n"
        "4. Spell out abbreviations on first use if the listener wouldn't know them.\n"
        "5. Add orienting connectives (\"Now,\" \"So,\" \"At this point,\") only at\n"
        "   paragraph transitions or after dense passages -- not every sentence.\n\n"
        "===============================================================\n"
        " PODCAST DEVICES (use with restraint -- hard caps below)\n"
        "===============================================================\n\n"
        "These are OPTIONAL and should only appear when they genuinely aid the listener.\n"
        "Do not force them.\n\n"
        "| Device                  | Cap per segment         | Guidance                                              |\n"
        "|-------------------------|-------------------------|-------------------------------------------------------|\n"
        "| Factual hook            | <=1, first sentence only | A single concrete fact that frames the segment. Must   |\n"
        "|                         |                         | come from the source text, not invented.               |\n"
        "| Signpost phrase         | <=2                      | Brief forward/backward references (\"Here's where it   |\n"
        "|                         |                         | gets interesting,\" \"To understand why, we need to...\").  |\n"
        "|                         |                         | Never more than one clause.                            |\n"
        "| Rhetorical question     | <=1                      | Only when the source itself poses or implies a         |\n"
        "|                         |                         | question. Do not manufacture curiosity gaps.           |\n"
        "| Emphasis micro-sentence | <=2                      | A short (<10 word) sentence that underscores a key     |\n"
        "|                         |                         | point. Must restate something already in the segment,  |\n"
        "|                         |                         | not add new commentary.                                |\n\n"
        "If the segment is under 80 words, skip all devices -- just do clean adaptation.\n\n"
        f"{tone_suffix}\n\n"
        "===============================================================\n"
        " ANTI-PATTERNS (reject these in your draft)\n"
        "===============================================================\n\n"
        "- Stacking 3+ short sentences in a row for dramatic cadence\n"
        "- Inserting \"And that changes everything\" / \"Let that sink in\" / \"Think about\n"
        "  that for a moment\" or any editorializing filler\n"
        "- Philosophical asides or thematic commentary not in the source\n"
        "- Repeating the same fact in different words for emphasis\n"
        "- Opening with \"Imagine...\" or \"Picture this...\" unless the source does\n"
        "- Addressing the listener as \"you\" more than once per segment\n"
        "- Trailing off with \"And that's just the beginning...\" cliffhanger bait\n"
        "  (unless the source itself sets up a continuation)\n\n"
        "===============================================================\n"
        " OUTPUT FORMAT\n"
        "===============================================================\n\n"
        "Return ONLY the rewritten narration for the current segment as plain text.\n\n"
        "- Preserve the original paragraph breaks (blank line between paragraphs).\n"
        "- No metadata, commentary, labels, or markdown.\n"
        "- No \"Here is the rewritten segment:\" preamble.\n"
    )


def build_spoken_delivery_retry_instructions(
    *,
    tone_preset: str,
    target_expansion_ratio: float,
    max_expansion_ratio: float,
) -> str:
    """Build the stricter retry prompt for spoken delivery."""

    tone_suffix = TONE_SUFFIXES.get(tone_preset, TONE_SUFFIXES["educational_suspenseful"])
    target_percent = int(round(target_expansion_ratio * 100))
    max_percent = int(round(max_expansion_ratio * 100))
    return (
        "Revise the previous spoken-delivery draft for the CURRENT SEGMENT.\n\n"
        "Your task is still an ADAPTATION for the ear, not a creative rewrite. Tighten\n"
        "the prose so it fits the length target while preserving the original meaning,\n"
        "facts, and structure.\n\n"
        "===============================================================\n"
        " TASK DEFINITION\n"
        "===============================================================\n\n"
        "Convert the CURRENT SEGMENT from written prose into spoken-word narration.\n\n"
        "This is an ADAPTATION for the ear, not a creative rewrite. Think of it as what\n"
        "a skilled audiobook editor does: restructure sentences for clarity when spoken,\n"
        "smooth over constructions that only work on the page, and add just enough\n"
        "connective tissue to keep a listener oriented -- without injecting new substance.\n\n"
        "===============================================================\n"
        " INPUT FORMAT\n"
        "===============================================================\n\n"
        "You will receive three clearly labeled blocks:\n\n"
        "  [PREVIOUS SEGMENT]  -- Read-only. For transition context only.\n"
        "  [CURRENT SEGMENT]   -- Rewrite THIS and only this.\n"
        "  [NEXT SEGMENT]      -- Read-only. For transition context only.\n\n"
        "Adjacent segments may be empty (start/end of episode). Never pull facts from\n"
        "adjacent segments into your output. Never relocate facts out of the current\n"
        "segment. The boundaries are hard walls.\n\n"
        "===============================================================\n"
        " INFORMATION FIDELITY (highest priority)\n"
        "===============================================================\n\n"
        "- Preserve ALL claims, facts, names, numbers, dates, and causal relationships.\n"
        "- Do not add examples, analogies, facts, or interpretations not in the source.\n"
        "- Do not upgrade hedged language (\"may\", \"some researchers believe\") to\n"
        "  definitive statements, or vice versa.\n"
        "- Do not merge or reorder paragraphs. Sentence-level reordering within a\n"
        "  paragraph is allowed only when it improves spoken flow without changing\n"
        "  meaning.\n"
        "- If a passage is highly technical or data-dense, prioritize clarity over\n"
        "  smoothness. It is better to sound slightly stiff than to lose precision.\n\n"
        "===============================================================\n"
        " LENGTH TARGET\n"
        "===============================================================\n\n"
        f"Output word count must fall between {target_percent}% and {max_percent}% of\n"
        "the current segment's word count.\n\n"
        f"If your draft exceeds {max_percent}%, cut connective filler first, then\n"
        "simplify phrasing. Do NOT cut facts to meet the target.\n\n"
        "===============================================================\n"
        " SPOKEN-FORM ADAPTATIONS (required)\n"
        "===============================================================\n\n"
        "Apply these mechanical transformations everywhere they help:\n\n"
        "1. Break any sentence longer than ~35 words into 2-3 shorter sentences.\n"
        "2. Merge back-to-back sentences under ~8 words into a single natural clause.\n"
        "3. Replace page-only constructions:\n"
        "   - Parentheticals -> separate sentence or appositive clause\n"
        "   - Semicolons -> period + short connective (\"And so...\", \"That meant...\")\n"
        "   - Dense noun stacks (>3 modifiers) -> unpack into a relative clause\n"
        "   - \"The former / the latter\" -> repeat the noun\n"
        "   - \"As shown in Figure X\" / \"See table below\" -> drop or replace with\n"
        "     a brief verbal restatement of the data point\n"
        "4. Spell out abbreviations on first use if the listener wouldn't know them.\n"
        "5. Add orienting connectives (\"Now,\" \"So,\" \"At this point,\") only at\n"
        "   paragraph transitions or after dense passages -- not every sentence.\n\n"
        "===============================================================\n"
        " PODCAST DEVICES (use with restraint -- hard caps below)\n"
        "===============================================================\n\n"
        "These are OPTIONAL and should only appear when they genuinely aid the listener.\n"
        "Do not force them.\n\n"
        "| Device                  | Cap per segment         | Guidance                                              |\n"
        "|-------------------------|-------------------------|-------------------------------------------------------|\n"
        "| Factual hook            | <=1, first sentence only | A single concrete fact that frames the segment. Must   |\n"
        "|                         |                         | come from the source text, not invented.               |\n"
        "| Signpost phrase         | <=2                      | Brief forward/backward references (\"Here's where it   |\n"
        "|                         |                         | gets interesting,\" \"To understand why, we need to...\").  |\n"
        "|                         |                         | Never more than one clause.                            |\n"
        "| Rhetorical question     | <=1                      | Only when the source itself poses or implies a         |\n"
        "|                         |                         | question. Do not manufacture curiosity gaps.           |\n"
        "| Emphasis micro-sentence | <=2                      | A short (<10 word) sentence that underscores a key     |\n"
        "|                         |                         | point. Must restate something already in the segment,  |\n"
        "|                         |                         | not add new commentary.                                |\n\n"
        "If the segment is under 80 words, skip all devices -- just do clean adaptation.\n\n"
        f"{tone_suffix}\n\n"
        "===============================================================\n"
        " ANTI-PATTERNS (reject these in your draft)\n"
        "===============================================================\n\n"
        "- Stacking 3+ short sentences in a row for dramatic cadence\n"
        "- Inserting \"And that changes everything\" / \"Let that sink in\" / \"Think about\n"
        "  that for a moment\" or any editorializing filler\n"
        "- Philosophical asides or thematic commentary not in the source\n"
        "- Repeating the same fact in different words for emphasis\n"
        "- Opening with \"Imagine...\" or \"Picture this...\" unless the source does\n"
        "- Addressing the listener as \"you\" more than once per segment\n"
        "- Trailing off with \"And that's just the beginning...\" cliffhanger bait\n"
        "  (unless the source itself sets up a continuation)\n\n"
        "===============================================================\n"
        " OUTPUT FORMAT\n"
        "===============================================================\n\n"
        "Return ONLY the rewritten narration for the current segment as plain text.\n\n"
        "- Preserve the original paragraph breaks (blank line between paragraphs).\n"
        "- No metadata, commentary, labels, or markdown.\n"
        "- No \"Here is the rewritten segment:\" preamble.\n"
    )
